### ISSUE TITLE
ci build can not be triggered. 

### ISSUE THREAD

**Issue by epiphyllum** [sameersbn/docker-runner-gitlab#3]
gitlab(7.9.1)  gitlab-ci(7.9.1) runner-gitlab(latest),  all  is setup successfully,  

but the ci build can not be triggered!!!

**Comment by epiphyllum** [comment]
the process of setup is like this:

1.  setup gitlab-ci application   and  in gitlab:

2.  use app_id  and secret_id as the env  parameter for  docker run of gitlab-ci,
    in gitlab-ci,   sync project with gitlab,  then add project to ci-builds

3. with the token get in step 2,  I follow the command in README.md, setup and run the runner-gitlab

4. add job for ci project and test it

5. push some commits to gitlab

**Comment by sameersbn** [comment]
@epiphyllum was your issue resolved? what was the issue?

**Comment by epiphyllum** [comment]
gitlab   need  gitlab-ci's   address.  
it is all about name resolving. 

add an entry in /etc/hosts of gitlab can fix it
xxx.xxx.xxx.xxx  gitlab-ci.tfs.com  

it seems that:;   gitlab gitlab-ci visit each other with name.  so we should add  /etc/hosts entry in both container
