### ISSUE TITLE
why my ci-build stay pending?

### ISSUE THREAD

**Issue by epiphyllum** [sameersbn/docker-runner-gitlab#4]
but the log shows that:   the runner consistently ask for new builds?

Started POST "/api/v1/builds/register.json" for 127.0.0.1 at 2015-04-09 17:50:42 +0800
Started POST "/api/v1/builds/register.json" for 127.0.0.1 at 2015-04-09 17:50:47 +0800
Started POST "/api/v1/builds/register.json" for 127.0.0.1 at 2015-04-09 17:50:52 +0800
Started POST "/api/v1/builds/register.json" for 127.0.0.1 at 2015-04-09 17:50:57 +0800
Started POST "/api/v1/builds/register.json" for 127.0.0.1 at 2015-04-09 17:51:02 +0800
Started POST "/api/v1/builds/register.json" for 127.0.0.1 at 2015-04-09 17:51:07 +0800
Started POST "/api/v1/builds/register.json" for 127.0.0.1 at 2015-04-09 17:51:12 +0800
Started POST "/api/v1/builds/register.json" for 127.0.0.1 at 2015-04-09 17:51:17 +0800
Started POST "/api/v1/builds/register.json" for 127.0.0.1 at 2015-04-09 17:51:22 +0800
Started POST "/api/v1/builds/register.json" for 127.0.0.1 at 2015-04-09 17:51:27 +0800

**Comment by epiphyllum** [comment]
![selection_002](https://cloud.githubusercontent.com/assets/8348065/7064441/40dac794-dee1-11e4-83d3-3324f92475f4.png)

**Comment by sameersbn** [comment]
@epiphyllum the `gitlab-ci-runner` polls the gitlab-ci server for builds. That is how the `gitlab-ci-runner` is implemented.

**Comment by epiphyllum** [comment]
the netwok is too slow.  sorry for the issue
